import Header from "@/components/ui/Header";
import "./globals.css";
import Footer from "@/components/ui/Footer";

export const metadata = {
 title: "Create Next App",
 description: "Generated by create next app",
};

export default function RootLayout({children}) {
 return (
  <html lang="en">
   <body className="h-full w-full">
    <Header />
    {children}
    <Footer />
   </body>
  </html>
 );
}
